[system]
		url =         "http://localhost:8080"
		upload=      "upload"
		transfer=    "transfer"
		m3u8 =        "media.m3u8"
		key_file =      "key"
		key_info_file = "KeyInfoFile"
[remote]

[callback]
       address = ""
       port =""
