[grpc]
    enable = true
#    type = "sock"
    port = ":7781"
    path = "/tmp/node.sock"
[rest]
    enable = true
[media]
    upload= "upload"
    transfer= "transfer"
    m3u8 = "media.m3u8"
    key_url = "http://localhost:8080"
    key_file = "key"
    key_dest = "output_key"
    key_info_file = "KeyInfoFile"

[queue]
    type = "redis"
    host_port = ":6379"
    password = ""
    db = 1
[ipfs]
    host = ""
    port = ""

[callback]
   type = "grpc"
   back_type = "unix"
   version = "v0"
   back_addr ="/tmp/manager.sock"
