
[media]
    upload= "upload"
    transfer= "transfer"
    m3u8 = "media.m3u8"
    key_url = "http://localhost:8080"
    key_file = "key"
    key_dest = "output_key"
    key_info_file = "KeyInfoFile"

[queue]
    type = "redis"
    host_port = ":6379"
    password = ""
    db = 1
[ipfs]
    host = ""
    port = ""

[callback]
   type = "grpc"
   back_type = "unix"
   version = "v0"
   back_addr ="/tmp/manager.sock"

[[oss]]
   endpoint ="https://oss-cn-shanghai.aliyuncs.com"
   access_key_id=""
   access_key_secret =""
   bucket_name =""

     [node]
         manager_name = "vlavr.grpc.manager"
         censor_name = "vlavr.grpc.censor"
         node_name = "vlavr.grpc.node"
         enable_grpc = true
         enable_rest = true
         request_type = "grpc"
       [node.rest]
         enable = false
         type = ""
         path = ""
         port = ":7787"